import { MockeReponse } from "../interfaces/IMockResponse";

export const getMockResponse = (id:number,name:string) => (
	{
		total_count: 16003,
		incomplete_results: false,
		items: [
			{
				id,
				node_id: "MDEwOlJlcG9zaXRvcnkxNDY3MjIzNzg=",
				name,
				full_name: "madhavanmalolan/awesome-reactnative-ui",
				private: false,
				owner: {
					login: "madhavanmalolan",
					id: 2111253,
					node_id: "MDQ6VXNlcjIxMTEyNTM=",
					avatar_url: "https://avatars.githubusercontent.com/u/2111253?v=4",
					gravatar_id: "",
					url: "https://api.github.com/users/madhavanmalolan",
					html_url: "https://github.com/madhavanmalolan",
					followers_url: "https://api.github.com/users/madhavanmalolan/followers",
					following_url: "https://api.github.com/users/madhavanmalolan/following{/other_user}",
					gists_url: "https://api.github.com/users/madhavanmalolan/gists{/gist_id}",
					starred_url: "https://api.github.com/users/madhavanmalolan/starred{/owner}{/repo}",
					subscriptions_url: "https://api.github.com/users/madhavanmalolan/subscriptions",
					organizations_url: "https://api.github.com/users/madhavanmalolan/orgs",
					repos_url: "https://api.github.com/users/madhavanmalolan/repos",
					events_url: "https://api.github.com/users/madhavanmalolan/events{/privacy}",
					received_events_url: "https://api.github.com/users/madhavanmalolan/received_events",
					type: "User",
					site_admin: false
				},
				html_url: "https://github.com/madhavanmalolan/awesome-reactnative-ui",
				description: "Awesome React Native UI components updated weekly",
				fork: false,
				url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui",
				forks_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/forks",
				keys_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/keys{/key_id}",
				collaborators_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/collaborators{/collaborator}",
				teams_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/teams",
				hooks_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/hooks",
				issue_events_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/issues/events{/number}",
				events_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/events",
				assignees_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/assignees{/user}",
				branches_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/branches{/branch}",
				tags_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/tags",
				blobs_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/blobs{/sha}",
				git_tags_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/tags{/sha}",
				git_refs_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/refs{/sha}",
				trees_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/trees{/sha}",
				statuses_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/statuses/{sha}",
				languages_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/languages",
				stargazers_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/stargazers",
				contributors_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/contributors",
				subscribers_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/subscribers",
				subscription_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/subscription",
				commits_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/commits{/sha}",
				git_commits_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/commits{/sha}",
				comments_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/comments{/number}",
				issue_comment_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/issues/comments{/number}",
				contents_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/contents/{+path}",
				compare_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/compare/{base}...{head}",
				merges_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/merges",
				archive_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/{archive_format}{/ref}",
				downloads_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/downloads",
				issues_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/issues{/number}",
				pulls_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/pulls{/number}",
				milestones_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/milestones{/number}",
				notifications_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/notifications{?since,all,participating}",
				labels_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/labels{/name}",
				releases_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/releases{/id}",
				deployments_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/deployments",
				created_at: "2018-08-30T08:50:14Z",
				updated_at: "2022-05-22",
				pushed_at: "2021-07-15T19:05:11Z",
				git_url: "git://github.com/madhavanmalolan/awesome-reactnative-ui.git",
				ssh_url: "git@github.com:madhavanmalolan/awesome-reactnative-ui.git",
				clone_url: "https://github.com/madhavanmalolan/awesome-reactnative-ui.git",
				svn_url: "https://github.com/madhavanmalolan/awesome-reactnative-ui",
				homepage: "",
				size: 138,
				stargazers_count: 3258,
				watchers_count: 3258,
				language: "Python",
				has_issues: true,
				has_projects: true,
				has_downloads: true,
				has_wiki: true,
				has_pages: false,
				forks_count: 330,
				mirror_url: null,
				archived: false,
				disabled: false,
				open_issues_count: 11,
				license: null,
				allow_forking: true,
				is_template: false,
				topics: [],
				visibility: "public",
				forks: 330,
				open_issues: 11,
				watchers: 3258,
				default_branch: "master",
				score: 1.0
			}
		]
	}

)

export const mockResponse:MockeReponse = {
    total_count: 1,
	incomplete_results: false,
	items: [
		{
			id: 146722378,
			node_id: "MDEwOlJlcG9zaXRvcnkxNDY3MjIzNzg=",
			name: "awesome-reactnative-ui",
			full_name: "madhavanmalolan/awesome-reactnative-ui",
			private: false,
			owner: {
				login: "madhavanmalolan",
				id: 2111253,
				node_id: "MDQ6VXNlcjIxMTEyNTM=",
				avatar_url: "https://avatars.githubusercontent.com/u/2111253?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/madhavanmalolan",
				html_url: "https://github.com/madhavanmalolan",
				followers_url: "https://api.github.com/users/madhavanmalolan/followers",
				following_url: "https://api.github.com/users/madhavanmalolan/following{/other_user}",
				gists_url: "https://api.github.com/users/madhavanmalolan/gists{/gist_id}",
				starred_url: "https://api.github.com/users/madhavanmalolan/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/madhavanmalolan/subscriptions",
				organizations_url: "https://api.github.com/users/madhavanmalolan/orgs",
				repos_url: "https://api.github.com/users/madhavanmalolan/repos",
				events_url: "https://api.github.com/users/madhavanmalolan/events{/privacy}",
				received_events_url: "https://api.github.com/users/madhavanmalolan/received_events",
				type: "User",
				site_admin: false
			},
			html_url: "https://github.com/madhavanmalolan/awesome-reactnative-ui",
			description: "Awesome React Native UI components updated weekly",
			fork: false,
			url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui",
			forks_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/forks",
			keys_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/keys{/key_id}",
			collaborators_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/collaborators{/collaborator}",
			teams_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/teams",
			hooks_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/hooks",
			issue_events_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/issues/events{/number}",
			events_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/events",
			assignees_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/assignees{/user}",
			branches_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/branches{/branch}",
			tags_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/tags",
			blobs_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/blobs{/sha}",
			git_tags_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/tags{/sha}",
			git_refs_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/refs{/sha}",
			trees_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/trees{/sha}",
			statuses_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/statuses/{sha}",
			languages_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/languages",
			stargazers_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/stargazers",
			contributors_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/contributors",
			subscribers_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/subscribers",
			subscription_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/subscription",
			commits_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/commits{/sha}",
			git_commits_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/git/commits{/sha}",
			comments_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/comments{/number}",
			issue_comment_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/issues/comments{/number}",
			contents_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/contents/{+path}",
			compare_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/compare/{base}...{head}",
			merges_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/merges",
			archive_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/{archive_format}{/ref}",
			downloads_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/downloads",
			issues_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/issues{/number}",
			pulls_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/pulls{/number}",
			milestones_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/milestones{/number}",
			notifications_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/notifications{?since,all,participating}",
			labels_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/labels{/name}",
			releases_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/releases{/id}",
			deployments_url: "https://api.github.com/repos/madhavanmalolan/awesome-reactnative-ui/deployments",
			created_at: "2018-08-30T08:50:14Z",
			updated_at: "2022-05-22",
			pushed_at: "2021-07-15T19:05:11Z",
			git_url: "git://github.com/madhavanmalolan/awesome-reactnative-ui.git",
			ssh_url: "git@github.com:madhavanmalolan/awesome-reactnative-ui.git",
			clone_url: "https://github.com/madhavanmalolan/awesome-reactnative-ui.git",
			svn_url: "https://github.com/madhavanmalolan/awesome-reactnative-ui",
			homepage: "",
			size: 138,
			stargazers_count: 3258,
			watchers_count: 3258,
			language: "Python",
			has_issues: true,
			has_projects: true,
			has_downloads: true,
			has_wiki: true,
			has_pages: false,
			forks_count: 330,
			mirror_url: null,
			archived: false,
			disabled: false,
			open_issues_count: 11,
			license: null,
			allow_forking: true,
			is_template: false,
			topics: [],
			visibility: "public",
			forks: 330,
			open_issues: 11,
			watchers: 3258,
			default_branch: "master",
			score: 1.0
		}
    ]
}

export const makeFakeError = () => ({
	message: "Validation Failed",
	errors: [
	  {
		"resource": "Search",
		"field": "q",
		"code": "missing"
	  }
	]
})

export const failedMockResponse = (totalCount:number) => (
	{
		"total_count": totalCount,
		"incomplete_results": false,
		"items": []
	}
)
